/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

public class App {

    public static void main(String... args) {
        HelloOtus.checkArgument();
    }
}
